
//Test Program for Grid class
//  Autogenerated by Class Wizard, by Stephen Wetzel, on April 19, 2014

#include "Grid.h" //
#include <iostream> //Basic input output (cout)
#include <string> //strings
#include <fstream> //file output
#include <sstream> //used to convert streams to strings
#include <ostream> //output streams
#include <vector> //vectors
using namespace std;


int main(int argc, char *argv[])
{
	
	Grid fileGrid("sample.txt");
	
	cout << fileGrid;
	int fillColumn;
	int fillRow;
	
	if (argc < 3)
	{//starting point was not passed, get it from user
		cout<<"\nEnter fill starting point: ";
		cin >> fillColumn >> fillRow;
	}
	else if (argc >= 3)
	{//starting point was passed in from command line
		istringstream ss1(argv[1]);
		ss1 >> fillColumn;
		
		istringstream ss2(argv[2]);
		ss2 >> fillRow;
	}
	
	fileGrid.floodFill(fillColumn, fillRow);
	
	cout << fileGrid;
	
  cout<<"\n\n"; //clean up output
  return 0;
}
